### PR TITLE
New files structure

### LINKED ISSUE #16: Learn what Tox is and integrate it with the project
For now I only know that Tox is used for automated testing

### PR DESCRIPTION
**Pull request by ferc255**
I edited our project's structure, added tests. Also I added setup files so that you can install project in editable mode. And now you can just type 'tox' if you want to run tests.

close #16

### CODE REVIEW

**Comment by esikachev** [comment]
This is a not good practice to include everything in one PR. One PR - one feature. Please, separate it

**Comment by ferc255** [comment]
@esikachev, what's the best way to do it from the current state?

**Comment by esikachev** [comment]
checkout from your master branch on a new branch with the feature name and add one feature and checkout from this branch to the new branch with another feature

**Comment by ferc255** [comment]
@esikachev, I've created new branch but I can't choose another donor branch now in this PR. 
cant_change_branch

**Comment by esikachev** [comment]
@ferc255 let's move discussion to the chat or direct messages

**Comment by ferc255** [comment]
@esikachev, I sent email on esikachov@gmail.com

**Pull request closed without merging**
