### PR TITLE
Added tox

### LINKED ISSUE #16: Learn what Tox is and integrate it with the project
For now I only know that Tox is used for automated testing

### PR DESCRIPTION
**Pull request by ferc255**
Added tox

close #16

### CODE REVIEW

**Comment by Andy-ch** [comment]
I think I've already seen "Renamed gen_training_data" somewhere already...

**Comment by ferc255** [comment]
@Andy-ch, @esikachev asked me to create 2 separate PR. #16 is invalid, never mind. I tried to do it different ways. Actually I'm a mess after all :D

**Comment by Andy-ch** [comment]
No, I don't even look at #17. I mean #18 - there is the same commit "Renamed gen_training_data". I think if they both are applied, there will be a merge conflict on the second one being applied
Is that right, @esikachev ?

**Comment by esikachev** [comment]
@Andy-ch yes, you are right. But in this case, we need to merge #18 before #19. @ferc255 add it to descriptions of PRs

**Comment by Andy-ch** [comment]
I guess I should apply travis to the project with tox rather than without it. But we need to take care of the conflict first

**Comment by ferc255** [comment]
@Andy-ch, there won't be conflicts. I suppose, the latest changes will be applied.

**Pull request merged**
