### PR TITLE
Added travis.yml

### PR DESCRIPTION
**Pull request by Andy-ch**
Also, updated requirements.txt

### CODE REVIEW

**Comment by esikachev** [comment]
CI is broken :)

**Comment by ferc255** [comment]
Right now it doesn't work because when travis started, the projects isn't in editable mode ([getting_started.rst](https://github.com/ssu-451/project/blob/master/docs/getting_started.rst)).

**Comment by esikachev** [comment]
You can try to add __init__.py here https://github.com/ssu-451/project/tree/master/ocr

**Comment by WalkingMike** [comment]
Its alive! Hooray!

**Pull request merged**
